from .userCreateView import UserCreateView
from .userDetailView import UserDetailView
from .createTarifaView import createTarifaView
from.createFacturaView import createFacturaView
from.createPlazasView import createPlazasView
from.createUsuariosView import createUsuariosView