# Generated by Django 3.2.8 on 2021-10-17 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parqueaderoapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plazas',
            fields=[
                ('idplazas', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_plaza', models.CharField(max_length=30)),
                ('codigo_plaza', models.CharField(max_length=30)),
                ('estado', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Tarifa',
            fields=[
                ('idtarifa', models.AutoField(primary_key=True, serialize=False)),
                ('precio_x_minuto', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('precio_fraccion', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('fraccion', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('idusuarios', models.AutoField(primary_key=True, serialize=False)),
                ('nombres', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=30)),
                ('user', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('tipo_identificacion', models.CharField(max_length=30)),
                ('identificacion', models.CharField(max_length=30)),
                ('correo', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('idfactura', models.AutoField(primary_key=True, serialize=False)),
                ('placa', models.CharField(max_length=30)),
                ('costo_total', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('tipo_vehiculo', models.CharField(max_length=30)),
                ('fecha_entrada', models.DateTimeField()),
                ('fecha_salida', models.DateTimeField()),
                ('id_plazask', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facidplazas', to='parqueaderoapp.plazas')),
                ('ususariok', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faciduser', to='parqueaderoapp.usuarios')),
            ],
        ),
    ]
